management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
spring:
  config:
    import: optional:file:.env
  application:
    name: inventory
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always