spring:
  application:
    name: inventory
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always